version: '3.8'

services:
  db:
    image: postgres:15
    container_name: volunteer_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: volunteer_data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: volunteer_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/volunteer_data

volumes:
  db_data:
